import {
  telefon,
  internet,
  dogalgaz,
  elektrik,
  aidat,
  yakit,
  emeklilik,
  market,
  oto,
  yemek,
  kredi_karti,
  kira,
  abone,
  okul_aidat,
  servis,
  atm,
  su,
  tatil,
  giyim,
  healty,
  ev_esya,
  cake,
  kitap,
  oyun,
  tadilat,
  money,
  love,
  fon,
  credit,
  bank,
  hotel,
  aile,
  diger,
  expenses,
  incomes,
} from "./icons";

export const butceCategoryData = [
  {
    id: 1,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "Telefon",
    icon: telefon,
  },
  {
    id: 2,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "İnternet/TV",
    icon: internet,
  },
  { id: 3, type: "Gider", categoryA: "Fatura", categoryB: "Su", icon: su },
  {
    id: 4,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "Doğalgaz",
    icon: dogalgaz,
  },
  {
    id: 5,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "Elektrik",
    icon: elektrik,
  },
  {
    id: 6,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "Site Aidat",
    icon: aidat,
  },
  {
    id: 7,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "Yakıt Parası",
    icon: yakit,
  },
  {
    id: 8,
    type: "Gider",
    categoryA: "Birikim",
    categoryB: "Bireysel Emeklilik",
    icon: emeklilik,
  },
  {
    id: 9,
    type: "Gider",
    categoryA: "Birikim",
    categoryB: "Fon Alım",
    icon: fon,
  },

  {
    id: 10,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Market",
    icon: market,
  },
  {
    id: 11,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Araç",
    icon: oto,
  },
  {
    id: 12,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Hazır Yemek",
    icon: yemek,
  },
  {
    id: 13,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Kredi",
    icon: kredi_karti,
  },
  {
    id: 14,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Kira",
    icon: kira,
  },
  {
    id: 15,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Abonelikler",
    icon: abone,
  },
  {
    id: 16,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Okul Aidatı",
    icon: okul_aidat,
  },
  {
    id: 17,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Servis Ücreti",
    icon: servis,
  },
  {
    id: 18,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "ATM Nakit",
    icon: atm,
  },
  {
    id: 35,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Tatil",
    icon: tatil,
  },
  {
    id: 19,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Giyim",
    icon: giyim,
  },
  {
    id: 20,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Sağlık",
    icon: healty,
  },
  {
    id: 21,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Ev Eşyası",
    icon: ev_esya,
  },
  {
    id: 22,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Pasta Hammadde",
    icon: cake,
  },
  {
    id: 23,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Eğitim/Kitap",
    icon: kitap,
  },
  {
    id: 24,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Eğlence/Oyun",
    icon: oyun,
  },
  {
    id: 25,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Ev Tadilat",
    icon: tadilat,
  },

  { id: 26, type: "Gelir", categoryA: "Maaş", categoryB: "", icon: money },
  { id: 27, type: "Gelir", categoryA: "Sena", categoryB: "", icon: love },
  { id: 28, type: "Gelir", categoryA: "Fon Satış", categoryB: "", icon: fon },
  { id: 29, type: "Gelir", categoryA: "Kredi", categoryB: "", icon: credit },
  { id: 30, type: "Gelir", categoryA: "Kıst Maaş", categoryB: "", icon: money },
  { id: 31, type: "Gelir", categoryA: "Promosyon", categoryB: "", icon: bank },
  { id: 32, type: "Gelir", categoryA: "Harcırah", categoryB: "", icon: hotel },
  { id: 33, type: "Gelir", categoryA: "Aile", categoryB: "", icon: aile },
  { id: 34, type: "Gelir", categoryA: "Diğer", categoryB: "", icon: diger },
];

export const menuItems = [
  {
    id: 1,
    title: "Gelir",
    icon: incomes,
    link: "/gelir",
  },
  {
    id: 2,
    title: "Gider",
    icon: expenses,
    link: "/gider",
  },
];

export const tarihSecim = [
  { id: 1, title: "Son 1 Ay" },
  { id: 2, title: "Son 3 Ay" },
  { id: 3, title: "Son 6 Ay" },
  { id: 4, title: "Son 1 Yıl" },
  { id: 5, title: "Son 3 Yıl" },
  { id: 6, title: "Tüm Zamanlar" },
];

export const totalCat = [
  "Toplam Gelir",
  "Toplam Gider",
  "Ortalama Aylık Gelir",
  "Ortalama Aylık Gider",
  "Gelir - Gider Farkı",
  "Tüm Zamanlar",
];
