exports.butceCategoryData = [
  {
    id: 1,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "Telefon",
  },
  {
    id: 2,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "İnternet/TV",
  },
  { id: 3, type: "Gider", categoryA: "Fatura", categoryB: "Su" },
  {
    id: 4,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "Doğalgaz",
  },
  {
    id: 5,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "Elektrik",
  },
  {
    id: 6,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "Site Aidat",
  },
  {
    id: 7,
    type: "Gider",
    categoryA: "Fatura",
    categoryB: "Yakıt Parası",
  },
  {
    id: 8,
    type: "Gider",
    categoryA: "Birikim",
    categoryB: "Bireysel Emeklilik",
  },
  {
    id: 9,
    type: "Gider",
    categoryA: "Birikim",
    categoryB: "Fon Alım",
  },

  {
    id: 10,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Market",
  },
  {
    id: 11,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Araç",
  },
  {
    id: 12,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Hazır Yemek",
  },
  {
    id: 13,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Kredi",
  },
  {
    id: 14,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Kira",
  },
  {
    id: 15,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Abonelikler",
  },
  {
    id: 16,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Okul Aidatı",
  },
  {
    id: 17,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "Servis Ücreti",
  },
  {
    id: 18,
    type: "Gider",
    categoryA: "Aylık Giderler",
    categoryB: "ATM Nakit",
  },
  {
    id: 35,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Tatil",
  },
  {
    id: 19,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Giyim",
  },
  {
    id: 20,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Sağlık",
  },
  {
    id: 21,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Ev Eşyası",
  },
  {
    id: 22,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Pasta Hammadde",
  },
  {
    id: 23,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Eğitim/Kitap",
  },
  {
    id: 24,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Eğlence/Oyun",
  },
  {
    id: 25,
    type: "Gider",
    categoryA: "Ekstra Giderler",
    categoryB: "Ev Tadilat",
  },

  { id: 26, type: "Gelir", categoryA: "Maaş", categoryB: "" },
  { id: 27, type: "Gelir", categoryA: "Sena", categoryB: "" },
  { id: 28, type: "Gelir", categoryA: "Fon Satış", categoryB: "" },
  { id: 29, type: "Gelir", categoryA: "Kredi", categoryB: "" },
  { id: 30, type: "Gelir", categoryA: "Kıst Maaş", categoryB: "" },
  { id: 31, type: "Gelir", categoryA: "Promosyon", categoryB: "" },
  { id: 32, type: "Gelir", categoryA: "Harcırah", categoryB: "" },
  { id: 33, type: "Gelir", categoryA: "Aile", categoryB: "" },
  { id: 34, type: "Gelir", categoryA: "Diğer", categoryB: "" },
];
